version: '3.4'

services:
  database:
    container_name: projeto-sd
    image: postgres:latest
    ports:
      - 6000:5432
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: admin 
      POSTGRES_DB: projeto-sd
  command-line:
    build:
     context: .
     dockerfile: Dockerfile
    command: tail -f /dev/null
    links: 
      - database
    volumes:
      - ..:/workspace
    